name: show_touches
description: "Show finger touch effects for Flutter, with support for multiple fingers, controllers, custom widgets, and animations."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
